import { StyleSheet } from "react-native";
import { colors } from "../../style"

export const loginStyles = StyleSheet.create({
    loginTriggerButton: {
        marginTop: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.acctBorder,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "transparent",
    },
    loginTriggerText: {
        fontSize: 16,
        fontWeight: "600",
        color: colors.acctText,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "flex-end",
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        marginBottom: -10,
    },
    modalContent: {
        backgroundColor: colors.acctCard,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 22,
        borderWidth: 1,
        borderColor: colors.acctBorder,
        borderBottomWidth: 0,
    },
    modalHandle: {
        alignSelf: "center",
        width: 40,
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.acctTextMuted,
        marginBottom: 16,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: colors.acctText,
        marginBottom: 20,
        textAlign: "center",
    },
    optionButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: colors.acctCardAlt,
        borderWidth: 1,
        borderColor: colors.acctBorder,
        marginBottom: 12,
    },
    optionIcon: {
        fontSize: 18,
    },
    optionText: {
        fontSize: 15,
        fontWeight: "600",
        color: colors.acctText,
    },
    divider: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 8,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: colors.acctBorder,
    },
    dividerText: {
        marginHorizontal: 10,
        fontSize: 13,
        color: colors.acctTextMuted,
    },
    tokenInputContainer: {
        marginBottom: 12,
    },
    tokenInput: {
        borderWidth: 1,
        borderColor: colors.acctBorder,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 15,
        color: colors.acctText,
        backgroundColor: colors.acctCardAlt,
        marginBottom: 12,
    },
    tokenSubmitButton: {
        backgroundColor: colors.acctAccent,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    tokenSubmitText: {
        color: colors.white,
        fontSize: 15,
        fontWeight: "600",
    },
    closeButton: {
        marginTop: 4,
        paddingVertical: 12,
        alignItems: "center",
    },
    closeButtonText: {
        fontSize: 15,
        color: colors.acctTextSecondary,
        fontWeight: "500",
    },
});